Mappings:
  RegionMap:
    us-east-1:
      "IMAGEID" : "ami-c481fad3"  
    us-east-2:
      "IMAGEID" : "ami-71ca9114" 
    us-west-1:
      "IMAGEID" : "ami-de347abe" 
    us-west-2:
      "IMAGEID" : "ami-b04e92d0" 
    ca-central-1:
      "IMAGEID" : "ami-eb20928f" 
    eu-west-1:
      "IMAGEID" : "ami-d41d58a7" 
    eu-central-1:
      "IMAGEID" : "ami-0044b96f"
    eu-west-2:
      "IMAGEID" : "ami-bfe0eadb" 
    ap-southeast-1:
      "IMAGEID" : "ami-7243e611" 
    ap-southeast-2:
      "IMAGEID" : "ami-55d4e436" 
    ap-northeast-2:
      "IMAGEID" : "ami-a04297ce" 
    ap-northeast-1:
      "IMAGEID" : "ami-1a15c77b"
    ap-south-1:
      "IMAGEID" : "ami-cacbbea5" 
    sa-east-1:
      "IMAGEID" : "ami-b777e4db"
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Your Required Environment Size (S,M,L)

Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 10
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] 
      DBName: xxxxxx
      Engine: MySQL
      MasterUsername: xxxxxx
      MasterUserPassword: xxxxxx
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", IMAGEID] 
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
  S3:
    Type: "AWS::S3::Bucket"

