Mappings:
  RegionMap:
    us-east-1:
      "IMAGEID" : "ami-a1234qwe" 
    us-east-2:
      "IMAGEID" : "ami-765ert89"
    ap-south-1:
      "IMAGEID" : "ami-98156bgr"
    us-west-1:
      "IMAGEID" : "ami-oplut34h" 
    us-west-2:
      "IMAGEID" : "ami-b30bhs82" 
    ca-central-1:
      "IMAGEID" : "ami-awslo345" 
    eu-central-1:
      "IMAGEID" : "ami-01losbnm" 
    eu-west-2:
      "IMAGEID" : "ami-poilabct" 
    ap-southeast-1:
      "IMAGEID" : "ami-12rtyu78" 
    ap-southeast-2:
      "IMAGEID" : "ami-9900rtvb"
    eu-west-1:
      "IMAGEID" : "ami-asoundtj" 
    ap-northeast-2:
      "IMAGEID" : "ami-xlrtpqce" 
    ap-northeast-1:
      "IMAGEID" : "ami-1quu778b" 
    sa-east-1:
      "IMAGEID" : "ami-b7b90sd5" 
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 10
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref SizeEnv, DB] 
      DataBaseName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", IMAGEID]
      InstanceType: !FindInMap [InstanceSize, !Ref SizeEnv, EC2]
      KeyName: KeyName
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: "AWS::S3::Bucket"

Parameters:
  SizeEnv:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - LARGE
    Description: Choose Your Required Size of Environment 
  DatabaseName:
    Type: String
    Default: xxxxxx
  DatabaseUser:
    Type: String
    Default: xxxxxx
  DatabasePassword:
    Type: String
    Default: xxxxxx
    NoEcho: true
